# Config file for automatic testing at travis-ci.org
language: python
python:
  - "3.6"
  - "pypy3"

# command to install dependencies
install:
  - pip install pipenv
  - pipenv install --system --deploy

script:
  - python --version
  - cd ./demo_client/mydumboclient_site_packages.mydumboclient/ && make dist && cd ../..
  - bubble --version
  - time behave
