# Config file for automatic testing at travis-ci.org
language: python
python:
  - "2.6"
  - "2.7"
  - "3.5"
  - "pypy"

#  - "pypy3", this runs but fails on one feature
# features/custom_local_client_encoding.feature
# current versions on travis
# Python 3.2.5 (b2091e973da6, Oct 19 2014, 18:29:55)
# [PyPy 2.4.0 with GCC 4.6.3

# command to install dependencies
install: "pip install -r travis_requirements.txt"

script:
  - python --version
  - cd ./demo_client/mydumboclient_site_packages.mydumboclient/ && make dist && cd ../..
  - cd ./demo_client/mydummyclient_bubble.clients.mydummyclient/ && make dist && cd ../..
  - make install
  - bubble --version
  - time behave
