# Config file for automatic testing at travis-ci.org
language: python
python:
  - "3.7"
  - "3.6"
  - "pypy3"

# command to install dependencies
install: "pip install -r travis_requirements.txt"

script:
  - python --version
  - cd ./demo_client/mydumboclient_site_packages.mydumboclient/ && make dist && cd ../..
  - pip install pipenv
  - pipenv install --system --deploy
  - bubble --version
  - time behave
