# Config file for automatic testing at travis-ci.org
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

# command to install dependencies
install:
  - pip install -r dev_requirements.txt -r requirements.txt -e .

script:
  - python --version
  - pip list
  - cd ./demo_client/mydumboclient_site_packages.mydumboclient/ && make dist && cd ../..
  - bubble --version
  - time behave
  - pip list
  - echo 'lets see after updated dependencies"
  - pip install -r dev_requirements.txt -r requirements.txt -e . -U
  - pip list
  - time behave
  - pip list
